In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define vocabulary size
voc_size=10000


In [5]:
# One hot
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6071, 4673, 9545, 752],
 [6071, 4673, 9545, 9994],
 [6071, 4410, 9545, 9011],
 [2910, 4972, 6918, 7767, 9121],
 [2910, 4972, 6918, 7767, 9997],
 [6572, 6071, 7453, 9545, 2710],
 [1459, 4818, 3470, 7767]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6071 4673 9545  752]
 [   0    0    0    0 6071 4673 9545 9994]
 [   0    0    0    0 6071 4410 9545 9011]
 [   0    0    0 2910 4972 6918 7767 9121]
 [   0    0    0 2910 4972 6918 7767 9997]
 [   0    0    0 6572 6071 7453 9545 2710]
 [   0    0    0    0 1459 4818 3470 7767]]


In [9]:
### Feature representation

dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   


 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 258ms/step


array([[[-0.01167077,  0.03434273, -0.03672131, -0.02380574,
          0.03608852,  0.00533388, -0.01327219, -0.02948057,
          0.04180968, -0.04105683],
        [-0.01167077,  0.03434273, -0.03672131, -0.02380574,
          0.03608852,  0.00533388, -0.01327219, -0.02948057,
          0.04180968, -0.04105683],
        [-0.01167077,  0.03434273, -0.03672131, -0.02380574,
          0.03608852,  0.00533388, -0.01327219, -0.02948057,
          0.04180968, -0.04105683],
        [-0.01167077,  0.03434273, -0.03672131, -0.02380574,
          0.03608852,  0.00533388, -0.01327219, -0.02948057,
          0.04180968, -0.04105683],
        [-0.0054576 ,  0.01104951, -0.01666838, -0.01035889,
         -0.0327587 ,  0.01840006,  0.01714829, -0.00748358,
         -0.04240446, -0.03815532],
        [-0.01470859,  0.03873762,  0.02079607,  0.03396162,
          0.0312431 ,  0.04589703, -0.02296745,  0.00607506,
         -0.03544067, -0.00838988],
        [ 0.00091385, -0.03590085, -0.03779498, -0.0